### ISSUE TITLE
How to run two effectful computations at once?

### ISSUE THREAD

**Issue by jackfirth** [effekt-lang/effekt#108]
I'm trying to model lazy streams in Effekt. I've got an effect representing a push-based producer of values and an effect representing a pull-based consumer of values, but I don't know how to combine these two things. It seems to require starting two computations and switching between them with `resume` somehow. Is what I'm trying to do possible? Here's the code I've got so far:

```
type Option[A] {
  Present(value: A);
  Absent()
}

effect Iterate[A] {
  def yield(element: A): Unit
}

effect Reduce[A] {
  def receive(): Option[A]
}

def inRange(start: Int, end: Int): Unit / Iterate[Int] = {
  do yield(start);
  if (start != end) inRange(start + 1, end);
}

def intoFold[A, S](initState: S) { f: (S, A) => S } : S / Reduce[A] =
  do receive[A]() match {
    case Present(a) => intoFold(f(initState, a)) { (s, a) => f(s, a) }
    case Absent() => initState
  }

def intoSum(): Int / Reduce[Int] = intoFold(0) { (s, a) => s + a }

def reduce[A, B]() { iterator: Unit => Unit / Iterate[A] } { reducer: Unit => B / Reduce[A] } = {
  try {
    reducer();
  } with Reduce[A] {
    def receive() = {
      try {
        iterator();
      } with Iterate[A] {
        def yield(element) = {
          // how to resume the outer reducer?
        }
      }
    }
  }
}
```

**Comment by phischu** [comment]
Wow, this is a very deep and hard question. Let me try to give you an actual answer, and then discuss some background.

Yes, it is possible, but only using brand new features. In fact exactly this problem was a key motivation for adding these features. I've also put the following piece of code [here](https://effekt-lang.org/examples/pushpull.html).

```
type Option[A] {
  Present(value: A);
  Absent()
}

effect Iterate[A] {
  def yield(element: A): Unit
}

effect Reduce[A] {
  def receive(): Option[A]
}

def inRange(start: Int, end: Int): Unit / Iterate[Int] = {
  do yield(start);
  if (start != end) inRange(start + 1, end);
}

def intoFold[A, S](initState: S) { f: (S, A) => S } : S / Reduce[A] =
  do receive[A]() match {
    case Present(a) => intoFold(f(initState, a)) { (s, a) => f(s, a) }
    case Absent() => initState
  }

def intoSum(): Int / Reduce[Int] = intoFold(0) { (s, a) => s + a }

def reduce[A, B]() { iterator: () => Unit / Iterate[A] } { reducer: () => B / Reduce[A] } = {
  var coroutine = fun() { Absent() };
  coroutine = fun() {
    try {
      iterator();
      Absent()
    } with Iterate[A] {
      def yield(e) = {
        coroutine = fun() { resume(()) };
        Present(e)
      }
    }
  };
  try {
    reducer()
  } with Reduce[A] {
    def receive() = {
      resume(coroutine())
    }
  }
}

def main() = {
  reduce[Int,Int]() { inRange(0, 5) } { intoSum() }
}
```
In [Effects, Capabilities, and Boxes](https://se.cs.uni-tuebingen.de/publications/brachthaeuser22effects/) we make it possible (among other things) to store computations in mutable references. Here we store a function in the mutable reference `coroutine` that when called will run `iterator` until the next yield and then update itself with the resumption. The innocent-looking line `resume(coroutine())` reads the current function from `coroutine`, unboxes it, calls it, and resumes with the result. If you hover over `coroutine` you will see that the value stored there is of type `() => Option[A] at {iterator, this}`. The function closes over `iterator` and the mutable reference itself, which lives in `this`. If you want to know more, please do ask.

We have some ongoing research on how to fuse a push stream and a pull stream, like we have in this example. In [Stream fusion to completeness](https://dl.acm.org/doi/10.1145/3093333.3009880) Oleg et al. write "Turning a non-linear stream to a producer involves “reifying” a stream: converting an α stream data type to essentially a (unit → α option) code function, which, when called, reports the new element or the end of the stream. We have to create a closure and generate and deconstruct the intermediate data type α option. There is no way around this: in one form or another, we have to capture the non-linear stream’s continuation." However, in the abstract of [an upcoming ICFP paper](https://icfp22.sigplan.org/details/ocaml-2022-papers/5/Highest-performance-Stream-Processing) Oleg et al. write "It supports finite and infinite streams with the familiar declarative interface, of _any_ combination of map, filter, take(while), drop(while), zip, flatmap combinators and tupling. [...] The library is based on assured code generation (at present, of OCaml and C) and guarantees in all cases _complete fusion_." Sadly I can't find a preprint.

Finally, this problem is connected to "shallow handlers" and indeed connecting two pipes is a classical example of their usefulness. We don't know if and how we can support shallow handlers directly.

**Comment by jackfirth** [comment]
Wow, that's awesome! I started playing around with this more, and I managed to reimplement the most complex parts of my transducers library from Racket in only a handful of lines. I put my results in [this gist](https://gist.github.com/jackfirth/f7bab2904aeba230f702febdfb45db67).

I'm gonna play around with this more, particularly as it relates to streaming libraries. I've made... far too many of those, so it's of particular interest to me.

**Comment by jackfirth** [comment]
I hit a problem that looks like a bug. In this code:

```
import immutable/list

type Option[A] {
  Present(value: A)
  Absent()
}

effect Iterate[A] {
  def emit(element: A): Unit
}

effect Reduce[A] {
  def consume(): Option[A]
}

def inRange(start: Int, end: Int): Unit / Iterate[Int] = {
  do emit(start)
  if (start != end) inRange(start + 1, end)
}

def intoList[A](): List[A] / Reduce[A] =
  do consume[A]() match {
    case Absent() => Nil()
    case Present(a) => Cons(a, intoList())
  }

def mapping[A, B] {f: A => B} : Unit / {Reduce[A], Iterate[B]} =
  do consume[A]() match {
    case Absent() => ()
    case Present(a) =>
      do emit(f(a))
      mapping {f}
  }

def reduce[A, B] {iterator: () => Unit / Iterate[A]} {reducer: () => B / Reduce[A]} = {
  var coroutine = fun() {Absent()}
  coroutine = fun() {
    try {
      iterator()
      Absent()
    } with Iterate[A] {
      def emit(e) = {
        coroutine = fun() {resume(())}
        Present(e)
      }
    }
  }
  try {
    reducer()
  } with Reduce[A] {
    def consume() = resume(coroutine())
  }
}

def transduce[A, B, C]
      {iterator: () => Unit / Iterate[A]}
      {transducer: () => Unit / {Reduce[A], Iterate[B]}}
      {reducer: () => C / Reduce[B]}
    : C = {
  reduce[A, C] {iterator} {reduce[B, C] {() => transducer()} {reducer}}
}

def works() = {
  reduce[Int, List[Int]] {inRange(0, 5)} {reduce[Int, List[Int]] {mapping[Int, Int] {x => x * x}} {intoList()}}
}

def fails() = {
  transduce[Int, Int, List[Int]] {inRange(0, 5)} {mapping[Int, Int] {x => x * x}} {intoList()}
}
```

The `works()` function works fine, but `fails()` raises this error at runtime:

```
TypeError: Reduce$capability_11863.op$consume is not a function
```

There's also some strangeness going on where the error isn't raised every time. I think that's some goofiness with the in-browser editor though. I haven't installed Effekt on my machine so I don't know how much of this is the online editor and how much of this is the Effekt compiler/runtime.

**Comment by b-studios** [comment]
Thanks @jackfirth for reporting this. I can confirm this bug also occurs in the installed version (non-online). I'll have to look into what the root cause is.

**Comment by b-studios** [comment]
I think the root cause is that the canonical ordering of inferred capabilities is not taken into account somewhere. This leads to arguments being in the wrong order as can be seen in the generated JS code:

```javascript
function mapping(f, Reduce$capability_1183, Iterate$capability_1184) {
    return Reduce$capability_1183.op$consume().then(((tmp965) =>
        $effekt.match(tmp965, [{
            pattern: $effekt.tagged("Absent"),
            exec: (() => { return $effekt.pure($effekt.unit); })
        }, {
            pattern: $effekt.tagged("Present", $effekt.any),
            exec: ((a) =>
                {
                    return f(a).then(((tmp966) =>
                        Iterate$capability_1184.op$emit(tmp966))).then((() =>
                        mapping(((a) => { return f(a); }), Iterate$capability_1184, Reduce$capability_1183)));
                })
        }])));
}
```
`mapping` first takes the `Reduce` capability and then the `Iterate` capability. However, in the recursive call the arguments are swapped.

**Comment by b-studios** [comment]
@jackfirth the flaky behavior you could observe probably arose from the fact that I used `hashCode` for the canonical ordering, which might not be stable enough.

**Comment by b-studios** [comment]
(Ah, I just noticed that I added your code to the tests without asking you :( I am sorry; please let me know if I should delete the tests again)

**Comment by jackfirth** [comment]
> (Ah, I just noticed that I added your code to the tests without asking you :( I am sorry; please let me know if I should delete the tests again)

Totally fine with me 😄 Glad I could contribute some useful example code!
