### ISSUE TITLE
Unhelpful error message when defining a value

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#130]
I found an unhelpful error message when I tried to create a variable/value whilst not remembering the grammar:

![image](https://user-images.githubusercontent.com/11269173/188677678-d1c560a8-4a57-40df-9896-bd1f66e86455.png)

**Comment by b-studios** [comment]
That's a tough one. The `unbox` operation (not visible) is inferred by [PreTyper](https://github.com/effekt-lang/effekt/blob/master/effekt/shared/src/main/scala/effekt/typer/PreTyper.scala) to fix the otherwise syntax incorrect program.

The problem is that sometimes this is the desired behavior (for instance when the result of `addOne` would be a function).

Do you have a suggestion on how to fix this?
