### ISSUE TITLE
`--compile` should generate executable

### ISSUE THREAD

**Issue by marzipankaiser** [effekt-lang/effekt#254]
Currently `--compile` just does not execute the generated code.
Instead, it should also generate some kind of executable at a known location
(e.g. by adding a shebang to the output, wrapping it, ...).

**Comment by dvdvgt** [comment]
I am afraid I don't fully grasp this issue.

- What kind of executable do you have in mind? How does this differ between the different backends, that is, does this only amount to changing the shebang, if we would choose to go into this direction or is there something else to take into consideration?
- Compiling it to a "known location" is already available via the `--out` option, no?
- What platforms do we want to target with this? Only UNIX systems or also Windows (shebangs won't work there)?

Can you perhaps eleborate a bit?

**Comment by b-studios** [comment]
Each Backend will need to decide what it constitutes to compile. Right now we already have abstractions in place where each backend can say how it compiles Effekt code. This should be extended to configure what `--compile` means.

**Comment by dvdvgt** [comment]
I think it might be good to have both options

1. `--compile`: Compile an Effekt source file to an executable.
2. `--source` (not exactly sure about the name yet): Transform an Effekt source file into the source language of the respective backend. This might be nice to have to manually inspect the generated code.

This means we would keep the current functionality of `--compile` and only rename it to `--source`. For the "new" `--compile` we take the output of `--source` and pass through some backend specific commands. For that, it would be helpful if you could let me know what this usually involves. That is, which backend specific commands do you typically manually invoke?

Something else to take into consideration is the IO involved here to call the backend specific compiler as a `Process`. Since the compiler seems to be prohibited from using IO, I would value your input here to which degree calling the backend specific compiler would break the invariant mentioned here:

https://github.com/effekt-lang/effekt/blob/523e11bea6c862935c86e84f8660a4d88574b95d/effekt/shared/src/main/scala/effekt/Compiler.scala#L84-L90

**Comment by b-studios** [comment]
Maybe we can keep `--compile` and call the new one `--build` ? @marzipankaiser @phischu any opinions?

**Comment by dvdvgt** [comment]
Resolved by PR #294.
