### ISSUE TITLE
Pass command-line arguments when running a program

### ISSUE THREAD

**Issue by IR0NSIGHT** [effekt-lang/effekt#300]
# expected behaviour:
WHEN i run 
```sh
effekt.sh myFile.effekt hello world
```
THEN myFile.effekt main() gets executed
AND commandLineArgs() returns ["hello","world"]

# observed behaviour:
WHEN i run 
```sh
effekt.sh myFile.effekt hello world
```
THEN myFile.effekt main() gets executed
AND throws:
```sh
hello (Datei oder Verzeichnis nicht gefunden)
world (Datei oder Verzeichnis nicht gefunden)
```
AND commandLineargs() evaluates to Nil() 

# Notes
i could not find a way to pass cmdargs directly into an execution.
currently i have to compile to js and call that file with the cmd args using Node.js

**Comment by b-studios** [comment]
Note that this is expected behavior and not a bug. You are asking for a new feature, which is to pass additional arguments to the command line when running a program. Right now, 

```
effekt.sh myFile.effekt hello world
```
will compile three effekt files `effekt.sh myFile.effekt`, `hello`, and `world`. 

We could deprecate this functionality in favour of your proposed behaviour. However, typically one would have a separate command line argument or separate additional arguments with `--` like

```
effekt.sh myFile.effekt -- hello world
```
